# Generated by Django 5.0 on 2023-12-21 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_type', models.CharField(choices=[('1', 'Daily'), ('2', 'Yearly'), ('3', 'Monthly')], max_length=40)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_payment', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Check OUT'), ('2', 'Check IN'), ('3', 'Reserved')], max_length=50, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=200, null=True)),
                ('category_name', models.CharField(max_length=40, null=True)),
                ('soft_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.IntegerField(null=True)),
                ('no_of_rooms', models.IntegerField(null=True)),
                ('soft_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'Admin'), ('2', 'Appartment'), ('3', 'Staff')], max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('1', 'Paid'), ('2', 'Pending'), ('3', 'Rejected')], max_length=50)),
                ('narration', models.CharField(blank=True, max_length=200, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_booking', to='bhtapt_web.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100)),
                ('yearly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('room_status', models.CharField(blank=True, choices=[('1', 'Check OUT'), ('2', 'Check IN'), ('3', 'Reserved')], max_length=200, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bhtapt_web.category')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bhtapt_web.floor')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhtapt_web.room'),
        ),
    ]
