# Generated by Django 5.0 on 2023-12-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0002_booking_category_floor_remove_user_is_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(blank=True, choices=[('1', 'Check OUT'), ('2', 'Check IN'), ('3', 'Reserved')], default='1', max_length=200, null=True),
        ),
    ]
