# Generated by Django 5.0 on 2023-12-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0003_alter_floor_floor_no_alter_room_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
