# Generated by Django 5.0 on 2023-12-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0004_category_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
