# Generated by Django 5.0 on 2023-12-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0005_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(blank=True, choices=[('1', 'Avaialable'), ('2', 'Booked')], default='1', max_length=200, null=True),
        ),
    ]
