# Generated by Django 5.0 on 2023-12-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0008_account_alter_room_room_number_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_no',
            field=models.CharField(blank=True, choices=[('1', 'Driving Licence'), ('2', 'Passport'), ('3', 'PAN Card')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_proof',
            field=models.CharField(blank=True, choices=[('1', 'Driving Licence'), ('2', 'Passport'), ('3', 'PAN Card')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(blank=True, choices=[('1', 'Avaialble'), ('2', 'Booked'), ('3', 'Reserved')], default='1', max_length=200, null=True),
        ),
    ]
