# Generated by Django 5.0 on 2023-12-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0009_booking_id_no_booking_id_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Booked'), ('3', 'Completed')], max_length=50, null=True),
        ),
    ]
