# Generated by Django 5.0 on 2023-12-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0010_alter_account_account_type_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
