# Generated by Django 5.0 on 2023-12-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0011_alter_booking_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='advance_payment',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
