# Generated by Django 5.0 on 2023-12-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0012_alter_booking_advance_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Booked'), ('3', 'Completed')], default='2', max_length=50, null=True),
        ),
    ]
