# Generated by Django 5.0 on 2023-12-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0017_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_remark',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
