# Generated by Django 5.0 on 2023-12-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0019_alter_account_balance_alter_booking_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
