# Generated by Django 5.0 on 2023-12-31 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0020_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from_account', to='bhtapt_web.account'),
        ),
    ]
