# Generated by Django 5.0 on 2023-12-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0024_alter_payment_to_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_account',
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
