# Generated by Django 5.0 on 2024-01-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0026_transaction_from_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_account',
        ),
    ]
