# Generated by Django 5.0 on 2024-01-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0027_remove_transaction_from_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cash_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_cash_payment', to='bhtapt_web.payment'),
        ),
        migrations.CreateModel(
            name='Cash_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('1', 'Paid'), ('2', 'Pending'), ('3', 'Rejected')], max_length=50)),
                ('narration', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cash_Payment_booking', to='bhtapt_web.booking')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cash_Payment_fromaccount', to='bhtapt_web.account')),
                ('to_account', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cash_Payment_toaccount', to='bhtapt_web.account')),
            ],
        ),
    ]
