# Generated by Django 5.0 on 2024-01-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0029_alter_transaction_cash_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_payment',
            name='payment_status',
            field=models.CharField(choices=[('1', 'Paid'), ('2', 'Pending'), ('3', 'Rejected')], default='1', max_length=50),
        ),
    ]
