# Generated by Django 5.0 on 2024-01-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0030_alter_cash_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_payment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashpayment_room', to='bhtapt_web.room'),
        ),
        migrations.AddField(
            model_name='payment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_room', to='bhtapt_web.room'),
        ),
        migrations.CreateModel(
            name='Journel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('1', 'Paid'), ('2', 'Pending'), ('3', 'Rejected')], default='1', max_length=50)),
                ('narration', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Journal_booking', to='bhtapt_web.booking')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_fromaccount', to='bhtapt_web.account')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journel_room', to='bhtapt_web.room')),
                ('to_account', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journel_toaccount', to='bhtapt_web.account')),
            ],
        ),
    ]
