# Generated by Django 5.0 on 2024-01-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0031_cash_payment_room_payment_room_journel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_journal', to='bhtapt_web.journel'),
        ),
    ]
