# Generated by Django 5.0 on 2024-01-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0032_transaction_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(blank=True, choices=[('1', 'Avaialble'), ('2', 'Booked'), ('3', 'Reserved'), ('4', 'Cleaning')], default='1', max_length=200, null=True),
        ),
    ]
