# Generated by Django 4.1.5 on 2024-03-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0036_alter_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Online')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id_proof',
            field=models.CharField(blank=True, choices=[('1', 'Driving Licence'), ('2', 'Passport'), ('3', 'PAN Card'), ('4', 'Adhaar Card'), ('5', 'Voter ID Card')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_proof',
            field=models.CharField(blank=True, choices=[('1', 'Driving Licence'), ('2', 'Passport'), ('3', 'PAN Card'), ('4', 'Adhaar Card'), ('5', 'Voter ID Card')], max_length=10, null=True),
        ),
    ]
