# Generated by Django 4.1.5 on 2024-03-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0037_booking_id_image_booking_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('tax', 'Tax'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
