# Generated by Django 4.1.5 on 2024-03-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtapt_web', '0038_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Online')], default='1', max_length=10, null=True),
        ),
    ]
